### ISSUE TITLE
A few small inconsistencies in the code and documentation for YolovV3 tutorial

### ISSUE THREAD

**Issue by Meeresgott** [LogicTronix/Vitis-AI-Reference-Tutorials#4]
Quantizing-Compiling-YOLOv3-Pytorch-with-DPU-Inference/README.md
Step 2.: 
```python
  python gpu_inference.py --quant_mode calib
  python gpu_inference.py --quant_mode test --batch_size 1 --deploy
```
Should be:
```python
  python quantize_yolov3.py --quant_mode calib
  python quantize_yolov3.py --quant_mode test --batch_size 1 --deploy
```
Quantizing-Compiling-YOLOv3-Pytorch-with-DPU-Inference/Quantization/quantize_result/README.md
```python
python quantize_yolov3.py --deploy_mode calib
python quantize_yolov3.py --deploy_mode test --batch_size 1 --deploy
```

Should be: 
```python
python quantize_yolov3.py --quant_mode calib
python quantize_yolov3.py  --quant_mode test --batch_size 1 --deploy
```

Quantizing-Compiling-YOLOv3-Pytorch-with-DPU-Inference/Quantized inference/quantized_inference.py line 14: 
```python
model = torch.jit.load('../Quantization/quantized_result/ModelMain_int.pt', map_location=torch.device('cpu'))
```
By renaming `quantized_result` to `quantize_result`, the location of the model must also be adjusted

```python
model = torch.jit.load('../Quantization/quantize_result/ModelMain_int.pt', map_location=torch.device('cpu'))
```

**Comment by Meeresgott** [comment]
I would rather not push it directly into the ticket: thank you! The tutorial helps me a lot right now. Thanks

**Comment by jinunyachhyon** [comment]
Thank you for taking the time to review the tutorial and provide feedback. I'm glad to hear that you're finding it helpful. Your insights are invaluable to us, and we'll definitely take them into account to improve the quality of our tutorial. If you have more suggestions or find any other issues, please don't hesitate to let us know!
