### ISSUE TITLE
target arguement

### ISSUE THREAD

**Issue by yadus97** [LogicTronix/Vitis-AI-Reference-Tutorials#6]
What should I give as target in arguements?

**Comment by jinunyachhyon** [comment]
Vitis AI offers a range of different Deep Learning Processing Units (DPUs) suitable for various Xilinx FPGA devices, including Xilinx Zynq UltraScale+ MPSoC, Kria KV260, Versal cards, and Alveo cards such as U50LV, U200, and U55C. These DPUs have their own DPU target names which should be given as "target" in arguments. 

#### For eg. DPUCZDX8G DPU with KV260 FPGA development board (used in this tutorial)

**Quantization Steps**
Step 1: "calib" 
```python
python quantize_yolov3.py --quant_mode calib --target DPUCZDX8G_ISA1_B4096
```
Step 2: "test" 
```python
python quantize_yolov3.py --quant_mode test --batch_size 1 --deploy --target DPUCZDX8G_ISA1_B4096
```
However, it is acceptable to quantize without passing the target name in "target" argument as well.
***
#### To access the target name:
```bash
cat opt/vitis_ai/compiler/arch/DPUCZDX8G/KV260/arch.json 
```
![image](https://github.com/LogicTronix/Vitis-AI-Reference-Tutorials/assets/85112312/65bdf214-ba3f-46da-a5f2-cc6f0acb2cdc)
***
You can find detailed information about hardware-aware quantization strategies in the Vitis AI documentation. Please refer the link provided: [Hardware-Aware Quantization Strategy](https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Hardware-Aware-Quantization-Strategy)

If you have any more questions or need further assistance, feel free to ask.

**Comment by yadus97** [comment]
Hi,
Thanks for the reply. I tried this, but still I was getting this error:  TypeError: __init__() got an unexpected keyword argument 'target'
